# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: | 
          curl --include--request POST--header "Content-Type: application/json; charset=utf-8"--data-binary "{\"app_id\": \"4d9ed678-fd57-4ed5-955d-4a28a609b275\",
          \"contents\": {\"en\": \"English Message\"},
          \"headings\": {\"en\": \"English Title\"},
          \"include_player_ids\": [\"52019eb2-31bf-41d4-a844-4366010b9faa\"]}"\
          https://onesignal.com/api/v1/notifications


        



