name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      
    - name: Use Java8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
          
    - name: intall gradle wrapper
      run: gradle wrapper
      
    - name: Build debug apk
      run: ./gradlew build
      
    - name: build release 
      run: ./gradlew assembleRelease

    - name: Create release and upload apk
      uses: underwindfall/create-release-with-debugapk@v2.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: Example.apk
        asset_content_type: application/zip
    
    
    
