name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      
    - name: Use Java8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
          
    - name: intall gradle wrapper
      run: gradle wrapper
   
    - name: Build debug apk
      run: cd android && ./gradlew build

    - name: Upload File
      id: upload
      uses: JantHsueh/upload-file-action@master
      with:
          url: https://www.pgyer.com/apiv2/app/upload
          forms: '{"_api_key":"${{ secrets.pgyer_key }}","buildInstallType":3}'
          fileForms: '{"file":"app/build/outputs/apk/debug/app-debug.apk"}'
    
    
    
