name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      
    - name: Use Java8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
          
    - name: intall gradle wrapper
      run: gradle wrapper
      
    - name: Build debug apk
      run: cd android && ./gradlew clean && ./gradlew build

#     - name: upload file apk
#       id: myRequest
#       run: curl -F email=dirk.duong.goldenowl@gmail.com -F file=@android/app/build/outputs/apk/debug/app-debug.apk https://srv-store1.gofile.io/uploadFile
    
    
    - name: 'Call API'
      uses: indiesdev/curl@v1
      id: api
      with:
        url: https://srv-store1.gofile.io/uploadFile
        method: 'POST'
        accept: 201
        body: '{ "email": "dirk.duong.goldenowl@gmail.com",  "file": "android/app/build/outputs/apk/debug/app-debug.apk" }'
    - name: 'Use response'
      run: echo ${{ steps.api.outputs.response }}

#     - name: Show Response
#       run: echo ${{ steps.myRequest.outputs.response }}
    
    
    
#     - name: Upload File
#       id: upload
#       uses: JantHsueh/upload-file-action@master
#       with:
#           url: https://www.pgyer.com/apiv2/app/upload
#           forms: '{"_api_key":"${{ secrets.pgyer_key }}","buildInstallType":3}'
#           fileForms: '{"file":"android/app/build/outputs/apk/debug/app-debug.apk"}'
    
    
    
